"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class ConfigFeedback(object):
    __slots__ = ["ConfigDataMd5"]

    def __init__(self):
        self.ConfigDataMd5 = ""

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(ConfigFeedback._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __ConfigDataMd5_encoded = self.ConfigDataMd5.encode('utf-8')
        buf.write(struct.pack('>I', len(__ConfigDataMd5_encoded)+1))
        buf.write(__ConfigDataMd5_encoded)
        buf.write("\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != ConfigFeedback._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ConfigFeedback._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = ConfigFeedback()
        __ConfigDataMd5_len = struct.unpack('>I', buf.read(4))[0]
        self.ConfigDataMd5 = buf.read(__ConfigDataMd5_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if ConfigFeedback in parents: return 0
        tmphash = (0xdddc6a97e8c38c20) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if ConfigFeedback._packed_fingerprint is None:
            ConfigFeedback._packed_fingerprint = struct.pack(">Q", ConfigFeedback._get_hash_recursive([]))
        return ConfigFeedback._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

